### ISSUE TITLE
Add maskable icon in manifest options

### ISSUE THREAD

**Issue by muhhizbe** [AllanChain/gridsome-plugin-pwa#16]
i'll add maskable icon in manifest options, how i do it?
I'll have like in link below
https://web.dev/maskable-icon-audit/?utm_source=lighthouse&utm_medium=devtools

**Comment by AllanChain** [comment]
@muhhizbe Please tell me which version of plugin you use and provide your options.

**Comment by muhhizbe** [comment]
> @muhhizbe Please tell me which version of plugin you use and provide your options. Big change in 0.3.0 :)
 0.2.5

**Comment by AllanChain** [comment]
[0.2.5 docs](https://github.com/AllanChain/gridsome-plugin-pwa/blob/v0.2.5/README.md)

```js
{
  maskableIcon: true
}
```

Should meet your need

**Comment by muhhizbe** [comment]
ohh yeah i see it, sorry i used 0.2.5 version but I configure with 0.3.0 option 😅
